from sqlalchemy import Float, ForeignKey, Integer, String
from sqlalchemy.orm import Mapped, mapped_column, relationship

from backend.app.models.base import Base


class Tag(Base):
    """A tag for categorizing photos (generated by AI vision model)."""

    __tablename__ = "tags"

    tag_id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
    name: Mapped[str] = mapped_column(String(200), unique=True, nullable=False)
    category: Mapped[str | None] = mapped_column(String(50))

    photo_tags: Mapped[list["PhotoTag"]] = relationship(back_populates="tag")


class PhotoTag(Base):
    """Association between a photo and a tag with confidence score."""

    __tablename__ = "photo_tags"

    file_hash: Mapped[str] = mapped_column(
        String(64), ForeignKey("photos.file_hash"), primary_key=True
    )
    tag_id: Mapped[int] = mapped_column(
        Integer, ForeignKey("tags.tag_id"), primary_key=True
    )
    confidence: Mapped[float | None] = mapped_column(Float)

    photo: Mapped["Photo"] = relationship(back_populates="tags")  # noqa: F821
    tag: Mapped["Tag"] = relationship(back_populates="photo_tags")
