import { useEffect, useState, useCallback } from "react";
import { api, type TagCount, type PhotoSummary } from "../api/client";
import { PhotoGrid } from "../components/PhotoGrid";
import { useStore } from "../store/useStore";
import { Loader2, Tag, ArrowLeft } from "lucide-react";

export function Tags() {
  const [tags, setTags] = useState<TagCount[]>([]);
  const [loading, setLoading] = useState(true);
  const [selectedTag, setSelectedTag] = useState<TagCount | null>(null);
  const [photos, setPhotos] = useState<PhotoSummary[]>([]);
  const [photosLoading, setPhotosLoading] = useState(false);
  const openViewer = useStore((s) => s.openViewer);

  useEffect(() => {
    async function load() {
      try {
        setLoading(true);
        const data = await api.getTags();
        setTags(data);
      } catch {
        // ignore
      } finally {
        setLoading(false);
      }
    }
    load();
  }, []);

  const handleSelectTag = useCallback(async (tag: TagCount) => {
    setSelectedTag(tag);
    setPhotosLoading(true);
    try {
      const data = await api.getTagPhotos(tag.tag_id, { page_size: 200 });
      setPhotos(data.items);
    } catch {
      // ignore
    } finally {
      setPhotosLoading(false);
    }
  }, []);

  const handleBack = useCallback(() => {
    setSelectedTag(null);
    setPhotos([]);
  }, []);

  const handlePhotoClick = useCallback(
    async (photo: PhotoSummary) => {
      try {
        const detail = await api.getPhoto(photo.file_hash);
        openViewer(detail);
      } catch {
        // ignore
      }
    },
    [openViewer]
  );

  if (loading) {
    return (
      <div className="flex items-center justify-center h-64">
        <Loader2 className="w-8 h-8 animate-spin text-primary-500" />
      </div>
    );
  }

  // Tag photo view
  if (selectedTag) {
    return (
      <div className="overflow-y-auto h-full">
        <div className="px-4 py-3 border-b border-gray-100 flex items-center gap-3">
          <button
            onClick={handleBack}
            className="p-1.5 rounded-lg hover:bg-gray-100 transition-colors"
          >
            <ArrowLeft className="w-5 h-5" />
          </button>
          <Tag className="w-5 h-5 text-gray-400" />
          <h1 className="text-lg font-semibold">
            {selectedTag.name}
            <span className="ml-2 text-gray-400 font-normal text-sm">
              {selectedTag.count} photo{selectedTag.count !== 1 ? "s" : ""}
            </span>
          </h1>
        </div>

        {photosLoading ? (
          <div className="flex items-center justify-center h-64">
            <Loader2 className="w-8 h-8 animate-spin text-primary-500" />
          </div>
        ) : (
          <PhotoGrid photos={photos} onPhotoClick={handlePhotoClick} />
        )}
      </div>
    );
  }

  // Tag list
  if (tags.length === 0) {
    return (
      <div className="flex flex-col items-center justify-center h-64 text-gray-400 gap-2">
        <Tag className="w-12 h-12 text-gray-300" />
        <p className="text-lg">No tags yet</p>
        <p className="text-sm">Tags are generated by the AI vision model during photo processing</p>
      </div>
    );
  }

  return (
    <div className="overflow-y-auto h-full">
      <div className="px-4 py-3 border-b border-gray-100">
        <h1 className="text-lg font-semibold">
          Tags
          <span className="ml-2 text-gray-400 font-normal text-sm">
            {tags.length} tag{tags.length !== 1 ? "s" : ""}
          </span>
        </h1>
      </div>

      <div className="flex flex-wrap gap-2 p-4">
        {tags.map((tag) => (
          <button
            key={tag.tag_id}
            onClick={() => handleSelectTag(tag)}
            className="inline-flex items-center gap-1.5 px-3 py-1.5 bg-gray-100 hover:bg-gray-200 rounded-full transition-colors text-sm"
          >
            <span className="font-medium text-gray-700">{tag.name}</span>
            <span className="text-xs text-gray-400">{tag.count}</span>
          </button>
        ))}
      </div>
    </div>
  );
}
